- name: mysql configuration
  hosts: mysql
  become: yes
  vars: 
    login_host: mysql.deepakaws.online
    mysql_password: "Expenseapp@1"
  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present
    
  - name: start the server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_password }}"
      login_host: "{{ login_host }}"
    register: mysql_info

  - name: print mysql info
    ansible.builtin.debug:
      msg: "mysql_info: {{ mysql_info }}"

  
