- name: "mysql"
  hosts: mysql
  become: yes
  vars:
    login_host: mysql.deepakaws.online
    password: ExpenseApp@1
  tasks:
  - name: ansible to install pymsql
    ansible.builtin.pip:
      name:
      - PyMySQL
      executable: pip3.9
  - name: "install mysql"
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: "start and enable the service"
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  
  - name: "Get the mysql info"
    community.mysql.mysql_info:
      login_user: root
      login_host: "{{ login_host }}"
      login_password: "{{ password }}"
    ignore_errors: true
    register: "mysql_info"

  - name: "print the mysql info"
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"

  - name: "Setting up the password"
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ password }}"
    when: mysql_info.failed is true

      